export const FETCH_NOTES = {
  SUCCESS: "FETCH_NOTES_SUCCES",
  FAILED: "FETCH_NOTES_FAILED"
};

export const CHANGE_NOTE_FIELD_VALUE = "CHANGE_NOTE_FIELD_VALUE";

export const CHANGE_IMPORTANCE = {
  SUCCESS: "CHANGE_IMPORTANCE_SUCCESS",
  FAILED: "CHANGE_IMPORTANCE_FAILED"
};

export const COPY_NOTE = {
  SUCCESS: "COPY_NOTE_SUCCESS",
  FAILED: "COPY_NOTE_FAILED"
};
export const DELETE_NOTE = {
  SUCCESS: "DELETE_NOTE_SUCCESS",
  FAILED: "DELETE_NOTE_FAILED"
};
export const POST_UPDATED_NOTE = {
  SUCCESS: "POST_UPDATED_NOTE_SUCCESS",
  FAILED: "POST_UPDATED_NOTE_FAILED"
};
export const ADD_NOTE = {
  SUCCESS: "ADD_NOTE_SUCCESS",
  FAILED: "ADD_NOTE_FAILED"
};
export const CHANGE_NOTE_COLOR = {
  SUCCESS: "CHANGE_NOTE_COLOR_SUCCESS",
  FAILED: "CHANGE_NOTE_COLOR_FAILED"
};

export const FETCH_LABELS = {
  SUCCESS: "FETCH_LABELS_SUCCES",
  FAILED: "FETCH_LABELS_FAILED"
};
export const ADD_LABEL = {
  SUCCESS: "ADD_LABELS_SUCCES",
  FAILED: "ADD_LABELS_FAILED"
};
export const UPDATE_LABEL = {
  SUCCESS: "UPDATE_LABELS_SUCCES",
  FAILED: "UPDATE_LABELS_FAILED"
};
export const DELETE_LABEL = {
  SUCCESS: "DELETE_LABELS_SUCCES",
  FAILED: "DELETE_LABELS_FAILED"
};
export const ADD_LABEL_TO_NOTE = {
         SUCCESS: "ADD_LABEL_TO_NOTE_SUCCES",
         FAILED: "ADD_LABEL_TO_NOTE_FAILED"
       };
export const DELETE_LABEL_FROM_NOTE = {
         SUCCESS: "DELETE_LABEL_FROM_NOTE_SUCCES",
         FAILED: "DELETE_LABEL_FROM_NOTE_FAILED"
       };

export const CHANGE_SIDEMENU_DISPLAY = 'CHANGE_SIDEMENU_DISPLAY'
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE'


